w4d2/NinetyNineCats/config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end

  resources :cat_rental_requests
end

w4d2/NinetyNineCats/app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = %w(calico blue grey black white tabby)

  has_many :cat_rental_requests,
    dependent: :destroy,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: "CatRentalRequest"

  validates :color, inclusion: { in: CAT_COLORS }
  validates :sex, inclusion: { in: %w(M F) }
  validates :color, :birth_date, :name, presence: true


  def age
    Date.today.year - self.birth_date.year
  end
end

w4d2/NinetyNineCats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :no_conflicting_requests

  belongs_to :requested_cat,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: "Cat"

  protected
  def overlapping_requests?
    !find_conflicts.empty?
  end

  def find_conflicts
    query = CatRentalRequest
      .where.not(id: self.id)
      .where(status: 'APPROVED')
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
        (start_date BETWEEN :start_date AND :end_date
          OR
        end_date BETWEEN :start_date AND :end_date)
      SQL
  end

  def no_conflicting_requests
    if overlapping_requests?
      self.errors[:base] << "Conflicting Approved Request Exists"
    end
  end
end

w4d2/NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4d2/NinetyNineCats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @requests = CatRentalRequest.all

  end

  def new
    @request = CatRentalRequest.new
  end

  def create
    @request = CatRentalRequest.new()
  end
end

w4d2/NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end
end

w4d2/NinetyNineCats/app/helpers/cat_rental_requests_controller_helper.rb
module CatRentalRequestsControllerHelper
end

w4d2/NinetyNineCats/app/views/cats/_form.html.erb
<label for="cat_name">Cat Name</label>
<input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">

<br>

<label for="cat_sex">Cat Sex</label>
<div>
  <input name="cat[sex]" id="cat_sex_m" type="radio" value="M" <%='checked'if @cat.sex == 'M' %> >
  <label for="cat_sex_m">Male</label>

  <input name="cat[sex]" id="cat_sex_f" type="radio" value="F"<%='checked'if @cat.sex == 'F' %>>
  <label for="cat_sex_f">Female</label>
</div>

<br>

<label for="cat_color">Color</label>
<select name="cat[color]">
  <option selected="selected"><%= @cat.color %></option>
  <%Cat::CAT_COLORS.each do |color| %>
  <option value="<%=color%>"><%=color.capitalize%></option>
  <%end%>
</select>

<br>

<label for="cat_birth_date">Birth Date</label>
<input name="cat[birth_date]" id="cat_birth_date" type="date" value="<%= @cat.birth_date %>">

<br>

<label for="cat_description">Description</label>
<textarea name="cat[description]" id="cat_description" ><%= @cat.description %></textarea>

<br>

  <input type="submit" value="Build my cat!">

w4d2/NinetyNineCats/app/views/cats/edit.html.erb
<h1> Edit Cat </h1>
<form action="<%=cat_url(@cat)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">

<%=render "form"%>

w4d2/NinetyNineCats/app/views/cats/index.html.erb
<h1>These our requests!</h1>

<ul><% @cats.each do |cat| %>
  <li><%= link_to cat.name, cat_url(cat) %></li>
  <%end%>
</ul>

w4d2/NinetyNineCats/app/views/cats/new.html.erb
<h1> Create a New Cat </h1>
<form action="<%=cats_url%>" method="POST">
  
<%=render "form"%>

w4d2/NinetyNineCats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <th>attributes</th>
  <% @cat.attributes.each do |k, v| %>
  <% next if k == 'created_at' || k == "updated_at" %>
  <% v = "(none)" if v.nil?  %>
  <tr>
    <td> <%= k %></td>
    <td> <%= v %></td>
  </tr>

  <% end %>

  <tr>
    <td>age</td>
    <td> <%= @cat.age %></td>
  </tr>

</table>

<%= link_to "edit me", edit_cat_url(@cat) %> 

w4d2/NinetyNineCats/app/views/cats/test.html.erb
<div>
<input name="cat[sex]" id="cat_sex_m" type="radio" value="M" >
</div>