w4d4/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session

  resources :bands do
    resources :albums, only: [:index]
  end

  resources :albums do
    resources :tracks, only: [:index, :new]
  end

  resources :tracks

end

w4d4/app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band,
    foreign_key: :band_id,
    primary_key: :id,
    class_name: "Band"
  has_many :tracks, dependent: :destroy

  validates :name, :band_id, presence: true
end

w4d4/app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums

  validates :name, presence: true
end

w4d4/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :track
  validates :user_id, :track_id, :note, presence: true
end

w4d4/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album
  has_many :notes

  validates :name, :album_id, presence: true
end

w4d4/app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes
  include UsersHelper
  attr_accessor :password
  validates :email, :password_digest, :session_token, presence: true
  validates :password, presence: true, allow_nil: true
  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def login!

  end

  def is_password? password
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials options
    user = User.find_by(email: options[:email])
    return nil unless user

    user.is_password?(options[:password]) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

end

w4d4/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @parent = nil
    @collection = Album.all
    render "shared/index"
  end
  def show
    @main = Album.find(params[:id])
    @parent = Band.find(@main.band_id)
    @collection = @main.tracks
    render "shared/index"
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.band_id = nil if @album.band_id == 0
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :recorded)
  end
end

w4d4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
   helper_method :current_user, :ensure_logged_in

   def login!(user)
     @current_user = user
     session[:session_token] = user.session_token
   end

   def current_user
     @current_user ||= User.find_by(session_token: session[:session_token])
   end

   def ensure_logged_in
     unless current_user
       flash[:errors] = "You must log in to view that page"
       redirect_to new_session_url
     end
   end
end

w4d4/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @bands = Band.all
  end

  def show
    @main = Band.find(params[:id])
    @collection = @main.albums
    render "shared/index"
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end
  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      fail
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w4d4/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user])
    if user.nil?
      flash.now[:errors] = "Invalid Credentials"
      render :new
    else
      user.reset_session_token!
      session[:session_token] = user.session_token
      redirect_to user_path(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to users_path
  end
end

w4d4/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :ensure_logged_in
  def index
    @collection = Track.all.sort_by(&:name)
    render "shared/index"
  end
  def show
    @track = Track.find(params[:id])
    @band = @track.band
    @notes = @track.notes
  end
  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to tracks_url
  end
  def new
    @track = Track.new
  end
  def create
    @track = Track.new(track_params)
    @track.bonus = (params[:track][:bonus] == "True" ? true : false)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end
  private
  def track_params
    params.require(:track).permit(:name, :album_id)
  end
end

w4d4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, only: [:index, :show, :create, :edit, :update, :destroy]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

w4d4/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/app/helpers/bands_helper.rb
module BandsHelper
end

w4d4/app/helpers/tracks_helper.rb
module TracksHelper
end

w4d4/app/helpers/users_helper.rb
module UsersHelper

end

w4d4/app/views/albums/index.html.erb
<h1>Lame Albums</h1>
<% if params[:band_id] %>
<h2>by <%= Band.find(params[:band_id].name) %></h2>
<% end %>
<ul>
  <% @albums.sort_by(&:name).each do |band| %>
  <li> <%=link_to band.name, band_path(band)%> </li>
  <%end%>
</ul>

w4d4/app/views/albums/new.html.erb
<h1>Create an album</h1>

<form action="<%=albums_url%>" method="post">
  <%= render "shared/auth_token" %>
  <label for="name">Name</label>
    <input type="text" id= "name" name="album[name]" value="<%= @album.name%>">
  <br><br>

  <label for="band">Band</label>
    <select id="band" name="album[band_id]">
      <option value=0>band name</option>
      <% Band.select(:name, :id).each do |band| %>
        <option value="<%=band.id%>">
          <%= band.name %> </option>
      <%end %>
    </select>
  <br><br>

  <label for="album_recording_type">Recording Type</label>
    <label id="album_recording_type" for="studio">Studio</label>
      <input type="radio" id="studio" name="album[recorded]" value="studio" checked>
    <label id="album_recording_type" for="live">Live</label>
      <input type="radio" id="live" name="album[recorded]" value="live">
  <br><br>
  <input type="submit">
</form>

w4d4/app/views/bands/index.html.erb
<h1>Lame Bands</h1>
<ul>
  <% @bands.sort_by(&:name).each do |band| %>
  <li> <%=link_to band.name, band_path(band)%> </li>
  <%end%>
</ul>

w4d4/app/views/bands/new.html.erb
<form action="<%= bands_url %>" method="post">
  <%=render "shared/auth_token"%>
  <label for="name">Name: </label>
  <input type="text" id="name" name="band[name]" value="<%=@band.name%>">
  <input type="submit">
</form>

w4d4/app/views/bands/show.html.erb
<!-- DEPRACATED!!!! USE SHARED/INDEX

<h1> <%= @band.name %> </h1>

<hX>Albums</hX>
<ul>
  <% @band.albums.each do |album| %>
  <li><%= link_to album.name, album_path(album) %></li>
  <% end %>
</ul>

<%= render "shared/destroy_button", object: @band %>

w4d4/app/views/users/edit.html.erb
<h1>Edit Name and/or Password</h1>

<form action="<%= user_url(@user) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= render "shared/auth_token" %>
  <%= render "shared/form", user: @user %>

w4d4/app/views/users/index.html.erb
<h1> Users </h1>

<ul>
<% @users.each do |user| %>
 <li> <%= link_to "view", user_path(user) %>: <%=user.attributes%></li>

<% end %>
<ul>

w4d4/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_path %>" method="post">

  <%= render "shared/auth_token" %>

  <%= render "shared/form", user: @user %>

w4d4/app/views/users/show.html.erb
<ul>
  <% @user.attributes.each do |k,v| %>
  <li>
    <%= k %>:
    <%= v %>
  </li>
  <% end %>
</ul>

<%= link_to "back to users index", users_path %>